[2024-06-18T12:25:00.690+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T12:25:00.724+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_ecomerc_pipeline_test_extract.load_cvs_to_staging manual__2024-06-18T12:25:00.164688+00:00 [queued]>
[2024-06-18T12:25:00.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_ecomerc_pipeline_test_extract.load_cvs_to_staging manual__2024-06-18T12:25:00.164688+00:00 [queued]>
[2024-06-18T12:25:00.733+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-18T12:25:00.743+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_cvs_to_staging> on 2024-06-18 12:25:00.164688+00:00
[2024-06-18T12:25:00.749+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_ecomerc_pipeline_test_extract', 'load_cvs_to_staging', 'manual__2024-06-18T12:25:00.164688+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ecom_dag.py', '--cfg-path', '/tmp/tmpenbs0mw2']
[2024-06-18T12:25:00.751+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3562) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T12:25:00.751+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask load_cvs_to_staging
[2024-06-18T12:25:00.752+0000] {standard_task_runner.py:63} INFO - Started process 3564 to run task
[2024-06-18T12:25:00.786+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_ecomerc_pipeline_test_extract.load_cvs_to_staging manual__2024-06-18T12:25:00.164688+00:00 [running]> on host 8f9202f823b8
[2024-06-18T12:25:00.974+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_ecomerc_pipeline_test_extract' AIRFLOW_CTX_TASK_ID='load_cvs_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T12:25:00.164688+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T12:25:00.164688+00:00'
[2024-06-18T12:25:00.976+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T12:25:00.989+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T12:25:00.990+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etl/extract_load_staging.py", line 10, in load_to_staging
    customers_df = pd.read_csv("/opt/airflow/data/csv/customers.csv")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/csv/customers.csv'
[2024-06-18T12:25:01.004+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_ecomerc_pipeline_test_extract, task_id=load_cvs_to_staging, run_id=manual__2024-06-18T12:25:00.164688+00:00, execution_date=20240618T122500, start_date=20240618T122500, end_date=20240618T122501
[2024-06-18T12:25:01.013+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task load_cvs_to_staging ([Errno 13] Permission denied: '/opt/airflow/data/csv/customers.csv'; 3564)
[2024-06-18T12:25:01.046+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T12:25:01.059+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T12:25:01.061+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
